name: furb_api
description: A simple command-line application.
version: 0.4.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  http:
  beautiful_soup_dart:

dev_dependencies:
  lints: ^1.0.0
